### ISSUE TITLE
Some avatars urls respond with 403 Forbidden 

### ISSUE THREAD

**Issue by tniezurawski** [Marak/faker.js#464]
This issue refers to `en` locale but it could potentially be a problem in other locales too.
When I try to GET some avatars I see 403 Forbidden.

I made a little investigation on this and checked this list: `faker.js/lib/locales/en/internet/avatar_uri.js`

So this is the list of 9 URLs that are not reachable:
https://s3.amazonaws.com/uifaces/faces/twitter/lindseyzilla/128.jpg
https://s3.amazonaws.com/uifaces/faces/twitter/kirillz/128.jpg
https://s3.amazonaws.com/uifaces/faces/twitter/nachtmeister/128.jpg
https://s3.amazonaws.com/uifaces/faces/twitter/flame_kaizar/128.jpg
https://s3.amazonaws.com/uifaces/faces/twitter/thinmatt/128.jpg
https://s3.amazonaws.com/uifaces/faces/twitter/cliffseal/128.jpg
https://s3.amazonaws.com/uifaces/faces/twitter/andychipster/128.jpg
https://s3.amazonaws.com/uifaces/faces/twitter/wr/128.jpg
https://s3.amazonaws.com/uifaces/faces/twitter/zacsnider/128.jpg

**Comment by Marak** [comment]
@tniezurawski -

It appears the source of avatar urls has been updated or changed?

Could you try to track this down and see where we can get the latest version of `uifaces`?

Thank you.

**Comment by tniezurawski** [comment]
@Marak I think that their [API is down](http://uifaces.com/api/v1/random). [They had problems before](http://uifaces.com/about) so I think the project is abandoned and I couldn't find any repository with more actual URLs.

I guess the solution is to just remove these 9 URLs and leave the rest. I checked them and all of them respond with 200. It's only 0.72% so not a big deal IMHO ;)

**Comment by Marak** [comment]
It kinda is a big deal, because it means users will have missing images `0.72%` of the time ( which is unacceptable ).

We should try and find a new source of images for the upcoming release. Any help would be appreciated.

Re: https://github.com/Marak/faker.js/issues/422

**Comment by tniezurawski** [comment]
@Marak 
> It kinda is a big deal, because it means users will have missing images 0.72% of the time ( which is unacceptable ).

**This is what's happening now.** That's the reason why I raised an issue ;)

If you remove these 9 URLs that are broken there is no chance that `faker.js` will pick broken URL again. I checked all of them (it's 1266 exactly).

**Comment by Marak** [comment]
Okay. Do you have a solution?

Just removing the broken ones isn't the best idea, as the source now seems to be compromised. No reason more won't go offline for no reason.

**Comment by tniezurawski** [comment]
I agree it's not the best solution as any of these URLs may go offline at any time but this will always work like this if you rely on 3rd party with a list of URLs :)

I'm afraid that without testing it every night you can't be 100% sure that you have a **hardcoded list** of still available images. So when you notice a dead link you can release a new version of this lib. (not very convenient)

The only solution IMO is too remove all these hardcoded URLs and rely on service like http://i.pravatar.cc/ '*
So you move the responsibility of delivering the right content to their site.

'* just an example as I don't know which service is the most reliable

**Comment by Marak** [comment]
CCing @calebogden ( creator of uifaces? )

**Comment by calebogden** [comment]
That S3 bucket is serving ~ 15M requests per month, the only reason those aren't working is the users deleted their account on UIFaces and so I deleted their images in S3 as well.

I don't mind people hotlinking to the S3 bucket but not sure how to handle the case where a user deletes their account. Ideally I'd have an endpoint where you could reference random / static accounts and fail gracefully but I haven't had time to rebuild.

**Comment by Marak** [comment]
@calebogden -

Thanks for the quick response!

Understood. I will remove the faces from faker and that should resolve our issue.

Does UIFaces get any funding for hosting these images? If we include them with future faker.js released, I'd expect you would get more traffic. I'm open to ideas to help make this work best for everyone.

**Comment by calebogden** [comment]
@Marak I had an ad unit on uifaces.com that paid for all hosting + S3 costs, and I've procured free hosting for the service moving forward so the S3 costs should be fine.

I'd love for faker.js to keep using uifaces. I'm rebuilding it to manage a few more digital assets than just avatars, after that's done I'll write an API that fails gracefully :)

**Comment by Marak** [comment]
@calebogden Super cool. Please let us know / open up a fresh issue if you have any updates to post for UIFaces.

Thanks again! UIFaces has been working nicely with faker for some time.

**Comment by Marak** [comment]
Removed old images. Should be resolved in next release.

**Comment by manwithsteelnerves** [comment]
We notice this issue when using faker.image.avatar() method where its returning image as https://s3.amazonaws.com/uifaces/faces/twitter/chacky14/128.jpg and is not found.

I updated to latest but still see the same issue.

**Comment by dawei-dai-exa** [comment]
@Marak Yes, same here. faker.iamage.avatar() not working retunr 403 forbidden

**Comment by calebogden** [comment]
Hi, unfortunately I had to shut down uifaces.com and the S3 bucket hosting
these images as the costs were getting out of control (over 10K in the past
few years)

**Comment by dherault** [comment]
So what is the new strategy to get random profile pictures?

**Comment by TakahiRoyte** [comment]
find alternative or build new one.

**Comment by dherault** [comment]
I used https://randomuser.me/photos in the meanwhile

**Comment by bchavez** [comment]
Hey there, does anyone have a backup copy of the S3 bucket contents of uifaces? I have a co-location at a local data center and would like to try hosting the S3 contents for users of Bogus.

Thanks,
Brian

**Comment by bchavez** [comment]
If anyone is interested, I was able to recover 1250 of 1254 avatars from the S3 bucket here: https://github.com/bchavez/Bogus/issues/336#issuecomment-731815283

**Comment by Grawl** [comment]
Just solved this problem. I found this page https://randomuser.me/photos where male and female photos are grouped into sections. I saved this page, then I wrote simple script to copy photos by group:

```sh
cp "53.jpg" women
cp "51.jpg" women
cp "61.jpg" women
...
cp "94(1).jpg" men
cp "20(1).jpg" men
cp "8(1).jpg" men
cp "38(1).jpg" men
...
```

then I used faker like this:

```js
import { men, women } from '../public/avatars'

const getPersonPhotos = gender => {
	switch (gender) {
		case 0:
			return [men, 'men']
		case 1:
			return [women, 'women']
		default:
			return [[], '']
	}
}

const getPersonPhoto = ({ gender }) => {
	const [photos, folderName] = getPersonPhotos(gender)
	const fileName = faker.random.arrayElement(photos)
	return `/avatars/${folderName}/${fileName}`
}

const gender = faker.random.number(1)
const photo = getPersonPhoto({ gender })
```

[avatars.zip](https://github.com/Marak/faker.js/files/5640683/avatars.zip)

<img src="https://user-images.githubusercontent.com/846774/101123479-b2c51780-3640-11eb-970c-eb3497541cf4.png" width=336>
